### ISSUE TITLE
在小米2中会闪退

### ISSUE THREAD

**Issue by zhehuaz** [linroid/FilterMenu#10]
系统版本 MIUI 5，基于Android 4.4.4

java.lang.RuntimeException: Unable to start activity ComponentInfo{org.bitnp.netcheckin2/org.bitnp.netcheckin2.ui.MainActivity}: android.os.BadParcelableException: ClassNotFoundException when unmarshalling: 
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2207)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2256)
at android.app.ActivityThread.access$800(ActivityThread.java:147)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1209)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:136)
at android.app.ActivityThread.main(ActivityThread.java:5133)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:515)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:808)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:624)
at dalvik.system.NativeStart.main(Native Method)
Caused by: android.os.BadParcelableException: ClassNotFoundException when unmarshalling: 
at android.os.Parcel.readParcelableCreator(Parcel.java:2154)
at android.os.Parcel.readParcelable(Parcel.java:2104)
at android.view.AbsSavedState.<init>(AbsSavedState.java:57)
at android.view.View$BaseSavedState.<init>(View.java:18684)
at com.linroid.filtermenu.library.FilterMenuLayout$SavedState.<init>(FilterMenuLayout.java:841)
at com.linroid.filtermenu.library.FilterMenuLayout$SavedState.<init>(FilterMenuLayout.java:812)
at com.linroid.filtermenu.library.FilterMenuLayout$SavedState$1.createFromParcel(FilterMenuLayout.java:852)
at com.linroid.filtermenu.library.FilterMenuLayout$SavedState$1.createFromParcel(FilterMenuLayout.java:850)
at android.os.Parcel.readParcelable(Parcel.java:2111)
at android.os.Parcel.readValue(Parcel.java:2020)
at android.os.Parcel.readSparseArrayInternal(Parcel.java:2382)
at android.os.Parcel.readSparseArray(Parcel.java:1742)
at android.os.Parcel.readValue(Parcel.java:2077)
at android.os.Parcel.readArrayMapInternal(Parcel.java:2321)
at android.os.Bundle.unparcel(Bundle.java:249)
at android.os.Bundle.getSparseParcelableArray(Bundle.java:1273)
at com.android.internal.policy.impl.PhoneWindow.restoreHierarchyState(PhoneWindow.java:1748)
at android.app.Activity.onRestoreInstanceState(Activity.java:970)
at android.app.Activity.performRestoreInstanceState(Activity.java:942)
at android.app.Instrumentation.callActivityOnRestoreInstanceState(Instrumentation.java:1138)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2175)
... 11 more

暂时只有在小米2和2A的旧系MIUI中发现了这个问题。

**Comment by linroid** [comment]
我这几天找台机器测试下~

2015-05-24 15:20 GMT+08:00 ZheHua Chang notifications@github.com:

> 系统版本 MIUI 5，基于Android 4.4.4
> 
> java.lang.RuntimeException: Unable to start activity
> ComponentInfo{org.bitnp.netcheckin2/org.bitnp.netcheckin2.ui.MainActivity}:
> android.os.BadParcelableException: ClassNotFoundException when
> unmarshalling:
> at
> android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2207)
> at
> android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2256)
> at android.app.ActivityThread.access$800(ActivityThread.java:147)
> at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1209)
> at android.os.Handler.dispatchMessage(Handler.java:102)
> at android.os.Looper.loop(Looper.java:136)
> at android.app.ActivityThread.main(ActivityThread.java:5133)
> at java.lang.reflect.Method.invokeNative(Native Method)
> at java.lang.reflect.Method.invoke(Method.java:515)
> at
> com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:808)
> at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:624)
> at dalvik.system.NativeStart.main(Native Method)
> Caused by: android.os.BadParcelableException: ClassNotFoundException when
> unmarshalling:
> at android.os.Parcel.readParcelableCreator(Parcel.java:2154)
> at android.os.Parcel.readParcelable(Parcel.java:2104)
> at android.view.AbsSavedState.(AbsSavedState.java:57)
> at android.view.View$BaseSavedState.(View.java:18684)
> at
> com.linroid.filtermenu.library.FilterMenuLayout$SavedState.(FilterMenuLayout.java:841)
> at
> com.linroid.filtermenu.library.FilterMenuLayout$SavedState.(FilterMenuLayout.java:812)
> at
> com.linroid.filtermenu.library.FilterMenuLayout$SavedState$1.createFromParcel(FilterMenuLayout.java:852)
> at
> com.linroid.filtermenu.library.FilterMenuLayout$SavedState$1.createFromParcel(FilterMenuLayout.java:850)
> at android.os.Parcel.readParcelable(Parcel.java:2111)
> at android.os.Parcel.readValue(Parcel.java:2020)
> at android.os.Parcel.readSparseArrayInternal(Parcel.java:2382)
> at android.os.Parcel.readSparseArray(Parcel.java:1742)
> at android.os.Parcel.readValue(Parcel.java:2077)
> at android.os.Parcel.readArrayMapInternal(Parcel.java:2321)
> at android.os.Bundle.unparcel(Bundle.java:249)
> at android.os.Bundle.getSparseParcelableArray(Bundle.java:1273)
> at
> com.android.internal.policy.impl.PhoneWindow.restoreHierarchyState(PhoneWindow.java:1748)
> at android.app.Activity.onRestoreInstanceState(Activity.java:970)
> at android.app.Activity.performRestoreInstanceState(Activity.java:942)
> at
> android.app.Instrumentation.callActivityOnRestoreInstanceState(Instrumentation.java:1138)
> at
> android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2175)
> ... 11 more
> 
> 暂时只有在小米2和2A的旧系MIUI中发现了这个问题。
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/linroid/FilterMenu/issues/10.

## 

---

_张林_

_湘潭大学软件工程2012级_

_Tel: 15574462423_

*GitHub: *https://github.com/linroid

*Blog: *http://linroid.com/
