### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by yoavst** [linroid/FilterMenu#17]
```
11-19 19:05:05.502 11148-11148/com.yoavst.mashov.debug E/Parcel: Class not found when unmarshalling:
                                                                 java.lang.ClassNotFoundException: Invalid name:
                                                                     at java.lang.Class.classForName(Native Method)
                                                                     at java.lang.Class.forName(Class.java:309)
                                                                     at java.lang.Class.forName(Class.java:273)
                                                                     at android.os.Parcel.readParcelableCreator(Parcel.java:2281)
                                                                     at android.os.Parcel.readParcelable(Parcel.java:2245)
                                                                     at android.view.AbsSavedState.<init>(AbsSavedState.java:57)
                                                                     at android.view.View$BaseSavedState.<init>(View.java:20270)
                                                                     at com.linroid.filtermenu.library.FilterMenuLayout$SavedState.<init>(FilterMenuLayout.java:853)
                                                                     at com.linroid.filtermenu.library.FilterMenuLayout$SavedState.<init>(FilterMenuLayout.java:830)
                                                                     at com.linroid.filtermenu.library.FilterMenuLayout$SavedState$1.createFromParcel(FilterMenuLayout.java:834)
                                                                     at com.linroid.filtermenu.library.FilterMenuLayout$SavedState$1.createFromParcel(FilterMenuLayout.java:832)
                                                                     at android.os.Parcel.readParcelable(Parcel.java:2252)
                                                                     at android.os.Parcel.readValue(Parcel.java:2152)
                                                                     at android.os.Parcel.readSparseArrayInternal(Parcel.java:2546)
                                                                     at android.os.Parcel.readSparseArray(Parcel.java:1874)
```

**Comment by magirtopcu** [comment]
Same issue for me.

**Comment by shico007** [comment]
Same issue for me.
